### ISSUE TITLE
How to use this Package

### ISSUE THREAD

**Issue by abbasmashaddy72** [MamdouhKhaled/tenancy-modules#1]
Hello Brother,

Your Package is Good But Need Documentation I can also help you with it just give me brief how to use it

@MamdouhKhaled

**Comment by Mamdouhkhalid** [comment]
yes plz
@abbasmashaddy72

**Comment by haithamRD** [comment]
hey @Mamdouhkhalid 
 there are any documentation for this package or just brief how to use it

**Comment by abbasmashaddy72** [comment]
> yes plz @abbasmashaddy72

I need a Brief how it works so that I can make the documentation after testing it

**Comment by haithamrdina** [comment]
@abbasmashaddy72  hey do you try to use this package ??

**Comment by abbasmashaddy72** [comment]
No, As I did not get a Brief on it, I had not used it

**Comment by haithamrdina** [comment]
@abbasmashaddy72 do you have any ideas on how to achieve this goal or any information on how to integrate laravel modules with tenancy for laravel?

**Comment by abbasmashaddy72** [comment]
I am getting started with it if there is any repo or blog about how to use it I will share hear @haithamrdina

**Comment by haithamrdina** [comment]
thank you @abbasmashaddy72

**Comment by haithamrdina** [comment]
any news about @abbasmashaddy72

**Comment by MamdouhKhaled** [comment]
@abbasmashaddy72 , @haithamrdina , @haithamRD 
I will write documents on how to use it and if on have any suggestions, I will be here

**Comment by haithamrdina** [comment]
okey @MamdouhKhaled  and if you need a help you can contact me

**Comment by haithamrdina** [comment]
thanks you so much @MamdouhKhaled

**Comment by MamdouhKhaled** [comment]
@haithamrdina 

If you have any problems or issue or suggestions I will be thankful

**Comment by abbasmashaddy72** [comment]
@MamdouhKhaled Thanks a lot brother
